VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ILoadedFromAddress"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Sub LoadFromAddress(ByVal lpAddress As LongPtr, Optional Index As Long = 0)

End Sub

Public Property Get OriginalAddress() As LongPtr

End Property
