VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IVbaVariableList"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get Count() As Long

End Property

Public Property Get Item(Index As Long) As IVbaVariable

End Property

Public Property Get Parent() As IVbaMethod

End Property

Public Function ToString() As String

End Function
