VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IVbaProjects"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get Count() As Long

End Property

Public Property Get Item(Index As Variant) As IVbaProject

End Property
'
'Public Function GetAddressByName(CallName As String) As LongPtr
'
'End Function
