VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IVbaProject"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit


Public Property Get FileName() As String

End Property

Public Property Get Name() As String

End Property

Public Property Get Objects() As IVbaObjects

End Property

Public Property Get Parent() As IVbaProjects

End Property

'Public Function GetAddressByName(CallName As String) As LongPtr
'
'End Function

